spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: Planista
server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${APP_PORT}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${JWT_EXP_ACCESS}
    refresh-expiration: ${JWT_EXP_REFRESH}