name: CI/CD (Gradle + Docker + VPS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_build:
    name: Test & Build (Gradle)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Gradle cache & wrapper
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew --no-daemon clean test

      - name: Build JAR
        run: ./gradlew --no-daemon bootJar

  docker_publish:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: test_build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: docker_publish
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ${{ secrets.GHCR_READ_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_READ_USER }} --password-stdin
            cd ${{ secrets.REMOTE_APP_DIR }}
            docker compose pull
            docker compose up -d
            docker image prune -f
